### ISSUE TITLE
Proxy Authentication

### ISSUE THREAD

**Issue by richrumble** [moullos/Mitigate#2]
Ran as local-admin, but behind an authenticated proxy and the "username or password is incorrect"
Can't elevate the domain user to "admin" in parts of our environment, have to use local accounts, or accounts that the auth-proxy won't be able to use.

Unhandled Exception: System.Security.Authentication.AuthenticationException: The user name or password is incorrect.
 ---> System.DirectoryServices.DirectoryServicesCOMException: The user name or password is incorrect.
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.PropertyValueCollection.PopulateList()
   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)
   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   --- End of inner exception stack trace ---
   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Mitigate.SystemUtils.IsDomainJoined()
   at Mitigate.Program.Main(String[] args)

**Comment by moullos** [comment]
Hi Rich,

This seems like a bug in the way that Mitig&te detects whether the machine is domain joined. 

I have altered the way that is done and push a fix. However, that won't be reflected in the pre-compiled versions for now. 

Also, keep in mind that I am working on a major upgrade to the project. Hopefully I will be able to release it before Christmas.

**Comment by richrumble** [comment]
Thanks I just recompiled, it still not working with authenticated proxies, or perhaps agents that force http/https connections to the auth proxy (BlueCoat WSS Agent).  Tried DeBug and Release just to be sure, no change in either.
Glad it doesn't bail as hard as it was prior :) 
Could there be a local copy of the "https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json" I could point the binary at, or can it look for that in the current dir perhaps?

-> Pulling latest ATT&CK matrix data from github.com/mitre/cti
-> Collecting some machine information. This might take some time...
-> The server could not be contacted.
Thanks!
-rich

**Comment by moullos** [comment]
Hey Rich,

I have added an 'AttackPath' flag for this. You can use -AttackPath='C:\Path\To\Attack\File' to point to the file on the machine. I have tested it on my test machine and it works as expected; let me know if you run into any issues.
